### ISSUE TITLE
2345<Title of Task>

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [TheBoatyMcBoatFace/Sandbox#41]
### Text To Summarize

"Confidential Information" means information or material which is proprietary to CivicActions and not generally known outside CivicActions, including information or material that you create, learn, or obtain, as well as information we receive in confidence from third parties. For example, this may include without limitation any information disclosed that is subject to applicable non-disclosure protections of CivicActions privacy policies, non-public product plans of CivicActions or 3rd parties, technical and business information, personnel information like salaries, or other sensitive information. Material need not be marked confidential for it to be considered Confidential Information.

**Comment by TheBoatyMcBotFace** [comment]
Hello TheBoatyMcBoatFace, Here is your summary
{"id":"cmpl-6ihdIJnEKducZdlaiJk6iu9C6hrAx","object":"text_completion","created":1676112176,"model":"text-davinci-003","choices":[{"text":"I've been a fan of the show since it first aired and have been hooked ever since. I've also been a fan of Supernatural since it began. I really love both shows and I'm always looking for new episodes and new ways to watch them. I've been looking for a way to watch Supernatural online, but I haven't been able to find anything that works. Does anyone know of a good website or service that I can use to watch Supernatural online?","index":0,"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":1,"completion_tokens":96,"total_tokens":97}}
